# -*- coding: utf-8 -*-
"""TP OpenData

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KdGRkG3u7-0kk2YGfqiRFPH9Muj2ob7v
"""

# Librerias
import requests
from bs4 import BeautifulSoup, NavigableString, Tag
import pandas as pd

nombres = []
precios = []


# Definición de URL y request de la información de la página
url = 'https://listado.mercadolibre.com.py/huawei#D[A:huawei]'
r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
lista = soup.find('ol', class_=  'ui-search-layout ui-search-layout--stack')


# Recoleccion de Nombre y Precio
for li in lista.find_all('li') : 
  nombre = li.find('a', class_ = 'ui-search-item__group__element ui-search-link').text
  nombres.append(nombre)

  precio = li.find('span', class_ = 'price-tag-amount').text
  precios.append(precio)
  
  

  


df = pd.DataFrame(list(zip(nombres, precios)))
df.columns = ['Nombre','Precio']

  
df.to_csv('Listado_de_productos.csv')

print(df)

"""# Sección nueva

# Sección nueva
"""